TakipProje/Models/LisansDetay.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LisansDetay
    {
        public int ID { get; set; }
        public string ProgramAd { get; set; }
        public System.DateTime ProgramTarih { get; set; }
        public Nullable<decimal> ProgramFiyat { get; set; }
        public Nullable<System.DateTime> ProgramBitisTarihi { get; set; }
    }
}

TakipProje/Controllers/LisansDetayController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TakipProje.Models;

namespace TakipProje.Controllers
{
    //[Authorize]
    public class LisansDetayController : Controller
    {
        private takipDbEntities db = new takipDbEntities();


        // GET: LisansDetay
        public ActionResult Index(string p)
        {
            var degerler = from d in db.LisansDetay select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.ProgramAd.Contains(p));
            }
            return View(degerler.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TakipProje/Views/LisansDetay/Index.cshtml
@model IEnumerable<TakipProje.Models.LisansDetay>

@{
    ViewBag.Title = "Lisans Tarihçe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Index", "LisansDetay", FormMethod.Get))
{

    <h2 class="title">Lisans Programlarının Geçmiş Fiyat Bilgileri</h2>
    <div class="search">
        @*Program Adı : @Html.TextBox("p")*@
        <label id="s_title" for="p">Program Adı : </label>
        <input type="text" name="p" size="80" placeholder="Aranacak Program Adını Giriniz . ." />&nbsp;&nbsp;&nbsp;
        <input style="transition:600ms" class="btn btn-outline-success" type="submit" value="Ara" />&nbsp;&nbsp;
        <button style="transition:600ms" class="btn btn-outline-primary" href="~/LisansDetay/Index">Aramayı Temizle</button>
        <button style="float: right;width:90px;text-align:center" type="button" class="btn btn-primary" onClick="location.href='/Lisans/Index'">Geri Dön</button>
    </div>
}

@*#466BD9 LEFTBAR CODE*@

<style>
    .title {
        text-align: center;
        margin: 30px;
        letter-spacing: 1px;
        padding: 15px;
        font-weight: lighter;
    }

    #s_title {
        font-weight: bolder;
        letter-spacing: 0.5px;
    }

    .search {
        border: solid gray 2px;
        margin: 15px;
        padding: 15px;
        margin: 10px;
        text-align: left;
    }

    .searchbox {
        width: 250px;
    }


</style>

<table id="lisansDetay" class="table table-striped table-bordered dt-responsive nowrap">
    <thead>
        <tr>
            <th>
                <p>
                    Program Adı
                </p>
            </th>
            <th>
                <p>
                    Alış Fiyatı
                </p>
            </th>
            <th>
                <p>
                    Alış Tarihi
                </p>
            </th>
            <th>
                <p>
                    Bitiş Tarihi Fiyatı
                </p>
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProgramAd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProgramFiyat) ₺
            </td>
            <td>
                @item.ProgramTarih.ToString("yyyy.MM.dd")
            </td>
            <td>
                @item.ProgramBitisTarihi.ToString("yyyy.MM.dd")
            </td>

        </tr>
        }
    </tbody>
</table>